name: "Danger JS"
on: pull_request

jobs:
  danger-js:
    name: Danger.js Checks
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Danger
      run: yarn danger ci -b main
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
