name: E2E Test

on: 
  push:
    paths:
      - 'Earthfile'
      - 'src/**'
      - 'tests/**'
      - 'assets/**'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '**.yml'
      - '!dangerfile.js'
      - '!.github'
      - '.github/workflows/e2e.yml'

jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10

      - name: Run Smoke Tests
        run: earthly github.com/edno/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-test

      - name: Check Docusaurus Production build
        run: earthly github.com/edno/graphql-markdown:${GITHUB_REF#refs/heads/}+docker
