name: Linter

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/linter.yml'

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run Prettier
      run: npm run prettier

    - name: Run ESLint
      run: npm run lint
