name: Linter

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'packages/**/*'
      - '.github/workflows/linter.yml'

jobs:
  lint:
    name: Lint ${{matrix.package}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['@graphql-markdown/docusaurus']

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run Prettier
      run: npm run prettier

    - name: Run ESLint
      run: npm run lint
