name: Linter

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'packages/**/*'
      - 'config/*'
      - '*.json'
      - '.github/workflows/linter.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run Prettier
      run: npm run prettier -- --check

    - name: Run ESLint
      run: npm run lint

    - name: Run Workspace dependencies check
      run: npm run check
