name: Linter

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'assets/**'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '**.yml'
      - '!dangerfile.js'
      - '!.github'
      - '.github/workflows/linter.yml'

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Run Prettier
      run: yarn prettier

    - name: Run ESLint
      run: yarn lint
