name: Mutation Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    paths:
      - "packages/**/src/**/*"
      - "packages/**/tests/**/*"
      - ".github/workflows/mutation.yml"

env:
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mutation:
    name: Mutation tests package ${{matrix.package}}
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            "core",
            "diff",
            "docusaurus",
            "printer-legacy",
            "utils",
            "helpers",
            "logger",
            "graphql",
          ]

    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4

      - name: Install modules
        run: npm ci

      - name: Run Mutations Tests
        run: |
          [ $(npm run test:ci -- --selectProjects @graphql-markdown/${{matrix.package}} --listTests --testMatch "<rootDir>/tests/unit/**/?(*.)+(spec|test).ts" | grep -i "test.ts" | wc -l) = "0" ] && exit 0
          npm run stryker -w @graphql-markdown/${{matrix.package}} -- --reporters dashboard --dashboard.module ${{matrix.package}}
