name: Mutation Test

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/src/**/*'
      - 'packages/**/tests/**/*'
      - '.github/workflows/mutation.yml'

env:
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

concurrency:
  group: mutation-testing
  cancel-in-progress: true

jobs:
  mutation:
    name: Mutation tests package ${{matrix.package}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['@graphql-markdown/docusaurus']

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run Mutations Tests
      run: npm run stryker -w ${{matrix.package}} -- --reporters dashboard
