name: Mutation Test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '**.js'
      - '!dangerfile.js'
      - '!.github'
      - '.github/workflows/mutation.yml'

env:
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

concurrency:
  group: mutation-testing
  cancel-in-progress: true

jobs:
  mutation:
    name: Mutation Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v3

    - name: Install modules
      run: yarn

    - name: Run Mutations Tests
      run: yarn stryker run --reporters dashboard
