name: Mutation Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - "packages/**/src/**/*"
      - "packages/**/tests/**/*"
      - ".github/workflows/mutation.yml"

env:
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

jobs:
  mutation:
    name: Mutation tests package ${{matrix.package}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["core", "diff", "docusaurus", "printer-legacy", "utils"]

    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Run Mutations Tests
        run: |
          [ $(npm test -- --selectProjects @graphql-markdown/${{matrix.package}} --listTests --testMatch "<rootDir>/tests/unit/**/?(*.)+(spec|test).ts" | grep -i "test.ts" | wc -l) = "0" ] && exit 0
          npm run stryker -w @graphql-markdown/${{matrix.package}} -- --reporters dashboard
