name: Smoke Tests

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'Earthfile'
      - 'packages/**'
      - '.github/workflows/smoke.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          version: latest

      - name: Run Smoke Tests
        run: earthly --ci github.com/graphql-markdown/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-test
        env:
          EARTHLY_NO_CACHE: true

      - name: Docusaurus Production Smoke Build without parameters and local schema
        run: earthly --ci github.com/graphql-markdown/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-run

      - name: Docusaurus Production Smoke Build with parameters and remote schema
        run: earthly --ci --build-arg OPTIONS="$OPTIONS" github.com/graphql-markdown/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-run
        env:
          OPTIONS: "--homepage data/anilist.md --schema https://graphql.anilist.co/ --force"

      - name: Docusaurus Production Smoke Build with groupByDirective option
        run: earthly --ci --build-arg OPTIONS="$OPTIONS" github.com/graphql-markdown/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-run
        env:
          OPTIONS: '--homepage data/groups.md --schema data/schema_with_grouping.graphql --groupByDirective @doc(category|=Common) --base group-by'
