name: Smoke Tests

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'Earthfile'
      - 'src/**'
      - 'tests/**'
      - 'assets/**'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '**.yml'
      - '!dangerfile.js'
      - '!.github'
      - '.github/workflows/e2e.yml'

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions/setup-earthly@v1

      - name: Run Smoke Tests
        run: earthly --ci github.com/edno/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-test

      - name: Docusaurus Production Smoke Build
        run: earthly --ci github.com/edno/graphql-markdown:${GITHUB_REF#refs/heads/}+build-demo
