name: Smoke Tests

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - 'Earthfile'
      - 'src/**'
      - 'tests/**'
      - 'assets/**'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '**.yml'
      - '!dangerfile.js'
      - '!.github'
      - '.github/workflows/smoke.yml'

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions/setup-earthly@v1

      - name: Run Smoke Tests
        run: earthly --ci github.com/edno/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-test
        env:
          EARTHLY_NO_CACHE: true

      - name: Docusaurus Production Smoke Build without parameters and local schema
        run: earthly --ci github.com/edno/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-run

      - name: Docusaurus Production Smoke Build with parameters and remote schema
        run: earthly --ci --build-arg OPTIONS="$OPTIONS" github.com/edno/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-run
        env:
          OPTIONS: "--homepage data/anilist.md --schema https://graphql.anilist.co/ --force"

      - name: Docusaurus Production Smoke Build with groupByDirective option
        run: earthly --ci --build-arg OPTIONS="$OPTIONS" github.com/edno/graphql-markdown:${GITHUB_REF#refs/heads/}+smoke-run
        env:
          OPTIONS: '--homepage data/groups.md --schema data/schema_with_grouping.graphql --groupByDirective @doc(category|=Common) --base group-by'
