name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]    
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'assets/**'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '**.yml'
      - '!dangerfile.js'
      - '!.github'
      - '!website'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Test Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run Unit Tests
      run: npm test -- --runInBand --projects packages/docusaurus/tests/unit

    - name: Run Integration Tests
      run: npm test -- --runInBand --projects packages/docusaurus/tests/integration

    - name: Check Code Coverage
      run: npm run test:coverage

    - name: Coveralls
      continue-on-error: true
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
