name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'packages/**/*'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Test ${{matrix.package}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['docusaurus']

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run Unit Tests
      run: |
        npm test -w @graphql-markdown/${{matrix.package}} -- --coverage --runInBand --selectProjects unit
        mkdir packages/${{matrix.package}}/.nyc_output/unit
        mv packages/${{matrix.package}}/.nyc_output/coverage-final.json packages/${{matrix.package}}/.nyc_output/unit/coverage-final.json

    - name: Run Integration Tests
      run: |
        npm test -w @graphql-markdown/${{matrix.package}} -- --coverage --runInBand --selectProjects integration
        mkdir packages/${{matrix.package}}/.nyc_output/integration
        mv packages/${{matrix.package}}/.nyc_output/coverage-final.json packages/${{matrix.package}}/.nyc_output/integration/coverage.json

    - name: Check Code Coverage
      run: npm run test:coverage -w @graphql-markdown/${{matrix.package}}

    - name: Coveralls
      continue-on-error: true
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./packages/${{matrix.package}}/coverage/lcov.info
        base-path: ./packages/${{matrix.package}}
