name: Test

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'assets/**'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '**.yml'
      - '!dangerfile.js'
      - '!.github'
      - '.github/workflows/test-win.yml'

jobs:
  test-windows:
    name: Test Code Base (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Run Unit Tests
      run: yarn test:ci --projects tests/unit

    - name: Run Integration Tests
      run: yarn test:ci --projects tests/integration
