name: Test

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'assets/**'
      - '**.js'
      - '**.json'
      - '**.yml'
      - '!dangerfile.js'
      - '!.github'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Test Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Run Unit Tests
      run: yarn test:ci --projects tests/unit

    - name: Run Integration Tests
      run: yarn test:ci --projects tests/integration

    - name: Check Code Coverage
      run: yarn test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
