name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'packages/**/*'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Test ${{matrix.package}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['@graphql-markdown/docusaurus']

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run Unit Tests
      run: |
        npm test -w ${{matrix.package}} -- --coverage --runInBand --selectProjects unit
        mv packages/docusaurus/coverage/coverage-final.json packages/docusaurus/coverage/coverage-unit.json

    - name: Run Integration Tests
      run: |
        npm test -w ${{matrix.package}} -- --coverage --runInBand --selectProjects integration
        mv packages/docusaurus/coverage/coverage-final.json packages/docusaurus/coverage/coverage-integration.json

    - name: Check Code Coverage
      run: npm run test:coverage -w ${{matrix.package}}

    - name: Coveralls
      continue-on-error: true
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
